/** Common Indian banks for the searchable dropdown (PRD Step 2). Not exhaustive; users can type any name. */
export const INDIAN_BANKS = [
  'State Bank of India',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'Punjab National Bank',
  'Bank of Baroda',
  'Canara Bank',
  'Union Bank of India',
  'IndusInd Bank',
  'Yes Bank',
  'IDFC First Bank',
  'Bank of India',
  'Central Bank of India',
  'Indian Bank',
  'Indian Overseas Bank',
  'UCO Bank',
  'Federal Bank',
  'RBL Bank',
  'Bandhan Bank',
  'AU Small Finance Bank',
  'Standard Chartered Bank',
  'Citibank',
  'HSBC Bank',
  'DBS Bank',
  'Punjab & Sind Bank',
  'Karur Vysya Bank',
  'South Indian Bank',
  'City Union Bank',
  'DCB Bank',
  'Jammu & Kashmir Bank',
  'Karnataka Bank'
]
